# Generated by Django 5.1.1 on 2025-11-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_time', models.IntegerField(choices=[(10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '1 hour'), (0, 'Custom')])),
                ('custom_time', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
